Fix typo and bump Typescript to 4.7 to fix build.
Before this, the typo caused a build error (presumably it used to get
past before someone decided to ban assigning to undeclared variables)
and build also failed with:

```
../../../node_modules/@types/node/events.d.ts(112,43): error TS2370: A rest parameter must be of an array type.
```

The idea to bump typescript came from here:
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/68895#discussioncomment-8685987